#! /bin/sh

ln -sf $PWD/bashrc ~/.bashrc
ln -sf $PWD/bashrc-pureza ~/.bashrc-pureza
ln -sf $PWD/inputrc ~/.inputrc
ln -sf $PWD/Xresources ~/.Xresources
ln -sf $PWD/emacs.d ~/.emacs.d
ln -sf $PWD/subversion/config ~/.subversion/config
